services:
    plex:
        image: lscr.io/linuxserver/plex:latest
        container_name: plex
        network_mode: host
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - VERSION=docker
            - PLEX_CLAIM=${PLEX_CLAIM}
        volumes:
            - /opt/docker/plex/app:/config
            - /mnt/media/series:/series
            - /mnt/media/movies:/movies
        devices:
            - /dev/dri:/dev/dri
        restart: unless-stopped

    gluetun:
        image: qmcgaw/gluetun
        container_name: gluetun
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        environment:
            - VPN_SERVICE_PROVIDER=protonvpn
            - OPENVPN_USER=${OPENVPN_USER}+pmp
            - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
            - SERVER_COUNTRIES=Netherlands
            - VPN_PORT_FORWARDING=on
            - TZ=${TZ}
        volumes:
            - /opt/docker/plex/gluetun:/gluetun
        ports:
            - 8080:8080 # qBittorrent WebUI
            - 9696:9696 # Prowlarr WebUI
            - 8191:8191 # Byparr WebUI
            - 6881:6881 # Torrent TCP
            - 6881:6881/udp # Torrent UDP
            - 7878:7878 # Radarr WebUI
            - 8989:8989 # Sonarr WebUI
        networks:
            - vpn
        restart: unless-stopped

    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        network_mode: "service:gluetun"
        depends_on:
            - gluetun
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - WEBUI_PORT=8080
        volumes:
            - /opt/docker/plex/qbittorrent/config:/config
            - /mnt/media/downloads:/downloads
        restart: unless-stopped

    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        network_mode: "service:gluetun"
        depends_on:
            - gluetun
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - /opt/docker/plex/sonarr:/config
            - /mnt/media/series:/series
            - /mnt/media/downloads:/downloads
        restart: unless-stopped

    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        network_mode: "service:gluetun"
        depends_on:
            - gluetun
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - /opt/docker/plex/radarr:/config
            - /mnt/media/movies:/movies
            - /mnt/media/downloads:/downloads
        restart: unless-stopped

    prowlarr:
        image: lscr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        network_mode: "service:gluetun"
        depends_on:
            - gluetun
            - byparr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - /opt/docker/plex/prowlarr:/config
        restart: unless-stopped

    byparr:
        image: ghcr.io/thephaseless/byparr:latest
        container_name: byparr
        network_mode: "service:gluetun"
        depends_on:
            - gluetun
        restart: unless-stopped

    overseerr:
        image: lscr.io/linuxserver/overseerr:latest
        container_name: overseerr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - /opt/docker/plex/overseerr:/config
        ports:
            - 5055:5055
        networks:
            - vpn
        restart: unless-stopped
    
    cloudflared:
        image: cloudflare/cloudflared:latest
        container_name: cloudflared
        network_mode: host
        volumes:
            - /opt/docker/plex/cloudflared:/etc/cloudflared
        command: tunnel run plex-tunnel
        restart: unless-stopped

    homarr:
        image: ghcr.io/homarr-labs/homarr:latest
        container_name: homarr
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /opt/docker/plex/homarr:/appdata
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_ENCRYPTION_KEY}
        ports:
            - 7575:7575
        networks:
            - vpn
        restart: unless-stopped

networks:
    vpn:
